const antiLeak = {
    //IP
    ipv4: /\b(?:\d{1,3}\.){3}\d{1,3}\b/,
    ipv6: /[a-fA-F\d]{1,4}(?::[a-fA-F\d]{1,4}){7}/,

    //Privé
    email: /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/,
    token: /[\w-]{24}\.[\w-]{6}\.[\w-]{27}|mfa\.[\w-]{84}/,

    //Numéro
    EUPhone: /\b(?:\+|00)[\d\s.-]{3,}[\d\s.-]+\b/,
    NAPhone: /\b(?:\+?1[-.]?)?(?:\(\d{3}\)|\d{3})[-.]?\d{3}[-.]?\d{4}\b/,

    //Carte
    Visa: /^4[0-9]{12}(?:[0-9]{3})?$/,
    Mastercard: /^5[1-5][0-9]{14}$/,
    Maestro: /^(?:5[0678]\d\d|6304|6390|67\d\d)\d{8,15}$/,
    AmericanExpress: /^3[47][0-9]{13}$/,
    Discover: /^6(?:011|5[0-9]{2})[0-9]{12}$/,
    DinersClub: /^3(?:0[0-5]|[68][0-9])[0-9]{11}$/,
    JCB: /^(?:2131|1800|35\d{3})\d{11}$/,

    //Confidentiels
    SSN: /\b\d{3}-\d{2}-\d{4}\b/,
    passport: /\b[A-Z0-9]{6,9}\b/,
    CVC: /\b\d{3,4}\b/,

    // Numéro de permis de conduire - Europe
    AlbaniaLicense: /^\d{9}$/i,
    AndorraLicense: /^[A-Z]{1}\d{5}$/i,
    AustriaLicense: /^\d{1,7}$/i,
    BelarusLicense: /^\d{1,9}$/i,
    BelgiumLicense: /^\d{11}$/i,
    BosniaHerzegovinaLicense: /^\d{9}$/i,
    BulgariaLicense: /^\d{9}$/i,
    CroatiaLicense: /^[A-Z]{2}\d{7}$/i,
    CyprusLicense: /^\d{6}$/i,
    CzechRepublicLicense: /^\d{8,10}$/i,
    DenmarkLicense: /^\d{9}$/i,
    EstoniaLicense: /^[A-Z0-9]{7}$/i,
    FinlandLicense: /^\d{9}$/i,
    FranceLicense: /^[0-9A-Z]{2}-\d{2}-\d{5}$/i,
    GermanyLicense: /^[A-ZÄÖÜ]{1,3}[A-ZÄÖÜ\d]{1}-\d{2}-\d{4}-\d{5}$/i,
    GreeceLicense: /^[A-Z]{1,2}\d{6}$/i,
    HungaryLicense: /^[A-Z0-9]{6}$/i,
    IcelandLicense: /^\d{7,10}$/i,
    IrelandLicense: /^[A-Z]{1}\d{7}$/i,
    ItalyLicense: /^\d{2}[A-Z]{1}\d{7}$/i,
    KosovoLicense: /^[A-Z]{2}\d{5}$/i,
    LatviaLicense: /^\d{8}$/i,
    LiechtensteinLicense: /^[A-Z]{2}\d{6}$/i,
    LithuaniaLicense: /^\d{11}$/i,
    LuxembourgLicense: /^\d{13}$/i,
    MaltaLicense: /^\d{7}$/i,
    MoldovaLicense: /^[A-Z]{2}\d{6}$/i,
    MonacoLicense: /^\d{6}$/i,
    MontenegroLicense: /^\d{9}$/i,
    NetherlandsLicense: /^\d{10}$/i,
    NorthMacedoniaLicense: /^\d{9}$/i,
    NorwayLicense: /^\d{9}$/i,
    PolandLicense: /^[A-Z0-9]{1}\d{8}$/i,
    PortugalLicense: /^\d{12}$/i,
    RomaniaLicense: /^\d{8,9}$/i,
    RussiaLicense: /^\d{10}$/i,
    SanMarinoLicense: /^\d{9}$/i,
    SerbiaLicense: /^\d{9}$/i,
    SlovakiaLicense: /^[A-Z0-9]{6,7}$/i,
    SloveniaLicense: /^[A-Z0-9]{1}\d{7}$/i,
    SpainLicense: /^[A-Z]{1}\d{7}$/i,
    SwedenLicense: /^\d{10}$/i,
    SwitzerlandLicense: /^[A-Z]{2}\d{6}$/i,
    TurkeyLicense: /^[A-Z]{2}\d{8}$/i,
    UkraineLicense: /^[A-Z]{2}\d{6}$/i,
    UnitedKingdomLicense: /^([A-Z]{2}\d{6}\w{2}[A-Z]{2})|(\d{16})$/i,
    VaticanCityLicense: /^\d{6}$/i,

    // Numéro de permis de conduire - Amérique du Nord
    USLicense: /^[A-Z]{1}\d{1}-\d{5}-\d{4}$/i,
    CanadaLicense: /^[A-Z]{1}\d{4}-\d{5}-\d{2}$/i,
    // Ajoutez d'autres pays d'Amérique du Nord ici...

    // Numéro de permis de conduire - Amérique du Sud
    ArgentinaLicense: /^[A-Z]{3}\d{6}$/i,
    BoliviaLicense: /^[A-Z]{2}\d{4}[A-Z]{1}$/i,
    BrazilLicense: /^[A-Z]{2}\d{4}\d{2}-\d{1}$/i,
    ChileLicense: /^\d{2}\.\d{3}\.\d{3}-\w{1}$/i,
    ColombiaLicense: /^\d{2}\d{3}\d{3}$/i,
    EcuadorLicense: /^[A-Z]{3}-\d{3}-\d{3}$/i,
    GuyanaLicense: /^[A-Z]{3}\d{4}$/i,
    ParaguayLicense: /^[A-Z]{2}\d{6}$/i,
    PeruLicense: /^[A-Z]{1,2}\d{5}$/i,
    SurinameLicense: /^[A-Z]{2}-\d{4}$/i,
    UruguayLicense: /^[A-Z]{3}\d{3}$/i,
    VenezuelaLicense: /^\d{2}-\d{5}$/i,

    // Numéro de permis de conduire - Afrique
    AlgeriaLicense: /^[A-Z]{2}\d{6}$/i,
    AngolaLicense: /^\d{9}$/i,
    BeninLicense: /^[A-Z]{2}\d{7}$/i,
    BotswanaLicense: /^[A-Z]{1}\d{9}$/i,
    BurkinaFasoLicense: /^\d{6}$/i,
    BurundiLicense: /^\d{6}$/i,
    CaboVerdeLicense: /^\d{9}$/i,
    CameroonLicense: /^\d{9}$/i,
    CentralAfricanRepublicLicense: /^[A-Z]{2}\d{6}$/i,
    ChadLicense: /^\d{11}$/i,
    ComorosLicense: /^[A-Z]{2}\d{7}$/i,
    CongoBrazzavilleLicense: /^\d{8}$/i,
    CongoKinshasaLicense: /^[A-Z]{1}\d{8}$/i,
    DjiboutiLicense: /^[A-Z]{2}\d{6}$/i,
    EgyptLicense: /^[A-Z]{1}\d{8}$/i,
    EquatorialGuineaLicense: /^[A-Z]{2}\d{6}$/i,
    EritreaLicense: /^\d{7}$/i,
    EswatiniLicense: /^\d{9}$/i,
    EthiopiaLicense: /^[A-Z]{1}\d{8}$/i,
    GabonLicense: /^[A-Z]{2}\d{6}$/i,
    GambiaLicense: /^[A-Z]{2}\d{5}$/i,
    GhanaLicense: /^[A-Z]{3}-\d{7}$/i,
    GuineaLicense: /^[A-Z]{2}\d{6}$/i,
    GuineaBissauLicense: /^[A-Z]{2}\d{6}$/i,
    IvoryCoastLicense: /^[A-Z]{2}\d{6}$/i,
    KenyaLicense: /^\d{8}$/i,
    LesothoLicense: /^\d{8}$/i,
    LiberiaLicense: /^[A-Z]{2}\d{6}$/i,
    LibyaLicense: /^[A-Z]{2}\d{6}$/i,
    MadagascarLicense: /^\d{11}$/i,
    MalawiLicense: /^[A-Z]{2}\d{6}$/i,
    MaliLicense: /^[A-Z]{2}\d{6}$/i,
    MauritaniaLicense: /^[A-Z]{2}\d{6}$/i,
    MauritiusLicense: /^[A-Z]{1}\d{8}$/i,
    MoroccoLicense: /^[A-Z]{2}\d{6}$/i,
    MozambiqueLicense: /^[A-Z]{2}\d{6}$/i,
    NamibiaLicense: /^[A-Z]{1}\d{7}$/i,
    NigerLicense: /^[A-Z]{2}\d{6}$/i,
    NigeriaLicense: /^[A-Z]{2}\d{6}$/i,
    RwandaLicense: /^\d{10}$/i,
    SaoTomeAndPrincipeLicense: /^[A-Z]{2}\d{6}$/i,
    SenegalLicense: /^[A-Z]{2}\d{6}$/i,
    SeychellesLicense: /^\d{7}$/i,
    SierraLeoneLicense: /^[A-Z]{2}\d{6}$/i,
    SomaliaLicense: /^\d{8}$/i,
    SouthAfricaLicense: /^[A-Z]{2}\d{6}$/i,
    SouthSudanLicense: /^\d{9}$/i,
    SudanLicense: /^[A-Z]{2}\d{6}$/i,
    TanzaniaLicense: /^\d{9}$/i,
    TogoLicense: /^[A-Z]{2}\d{6}$/i,
    TunisiaLicense: /^\d{8}$/i,
    UgandaLicense: /^\d{9}$/i,
    ZambiaLicense: /^[A-Z]{2}\d{6}$/i,
    ZimbabweLicense: /^\d{8}$/i,

    // Numéro de permis de conduire - Asie
    AfghanistanLicense: /^\d{9}$/i,
    ArmeniaLicense: /^[A-Z]{2}\d{6}$/i,
    AzerbaijanLicense: /^[A-Z]{2}\d{7}$/i,
    BahrainLicense: /^[A-Z]{2}\d{4}$/i,
    BangladeshLicense: /^[A-Z]{2}-\d{8}$/i,
    BhutanLicense: /^[A-Z]{2}\d{5}$/i,
    BruneiLicense: /^[A-Z]{2}\d{5}$/i,
    CambodiaLicense: /^\d{9}$/i,
    ChinaLicense: /^[A-Z]{1}\d{7}$/i,
    CyprusLicense: /^\d{6}$/i,
    GeorgiaLicense: /^\d{9}$/i,
    IndiaLicense: /^[A-Z]{2}\d{13}$/i,
    IndonesiaLicense: /^[A-Z]{1}\d{12}$/i,
    IranLicense: /^\d{8}$/i,
    IraqLicense: /^\d{10}$/i,
    IsraelLicense: /^\d{9}$/i,
    JapanLicense: /^[A-Z]{2}\d{6}$/i,
    JordanLicense: /^\d{8}$/i,
    KazakhstanLicense: /^[A-Z]{2}\d{6}$/i,
    KuwaitLicense: /^[A-Z]{2}\d{6}$/i,
    KyrgyzstanLicense: /^[A-Z]{2}\d{6}$/i,
    LaosLicense: /^[A-Z]{2}\d{6}$/i,
    LebanonLicense: /^[A-Z]{2}\d{6}$/i,
    MalaysiaLicense: /^[A-Z]{1}\d{12}$/i,
    MaldivesLicense: /^[A-Z]{2}-\d{4}-\d{5}$/i,
    MongoliaLicense: /^[A-Z]{2}\d{6}$/i,
    MyanmarLicense: /^[A-Z]{1}\d{7}$/i,
    NepalLicense: /^[A-Z]{2}\d{6}$/i,
    NorthKoreaLicense: /^[A-Z]{2}\d{6}$/i,
    OmanLicense: /^[A-Z]{1}\d{7}$/i,
    PakistanLicense: /^[A-Z]{2}-\d{5}-\d{2}$/i,
    PalestineLicense: /^[A-Z]{2}\d{6}$/i,
    PhilippinesLicense: /^[A-Z]{2}\d{6}$/i,
    QatarLicense: /^[A-Z]{2}\d{6}$/i,
    SaudiArabiaLicense: /^\d{10}$/i,
    SingaporeLicense: /^[A-Z]{2}\d{6}$/i,
    SouthKoreaLicense: /^[A-Z]{2}\d{6}$/i,
    SriLankaLicense: /^\d{9}$/i,
    SyriaLicense: /^\d{11}$/i,
    TaiwanLicense: /^[A-Z]{1}\d{8}$/i,
    TajikistanLicense: /^[A-Z]{2}\d{6}$/i,
    ThailandLicense: /^[A-Z]{2}\d{6}$/i,
    TimorLesteLicense: /^\d{9}$/i,
    TurkmenistanLicense: /^[A-Z]{2}\d{6}$/i,
    UnitedArabEmiratesLicense: /^\d{7}$/i,
    UzbekistanLicense: /^[A-Z]{2}\d{6}$/i,
    VietnamLicense: /^[A-Z]{2}\d{7}$/i,
    YemenLicense: /^[A-Z]{2}\d{6}$/i,
};
  
module.exports = antiLeak;